--Q6 Find the number of customers from each country.

select
country,
count(customer_id) as no_of_customer
from customers
group by country;

--Q7 Find the number of orders placed by each customer.

select
customer_id,
count(order_id) as no_of_orders
from orders
group by customer_id;

--Q8 Find customers who have never placed an order.

SELECT
    c.customer_id,
    c.customer_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

--Q9 Find the total quantity purchased by each customer.

select customer_id,
sum(quantity) as total_quantity
from orders
group by customer_id;

--Q10 Find the total revenue generated by each customer.

SELECT 
    c.customer_id,
    c.customer_name,
    SUM(p.price * o.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN products p
    ON p.product_id = o.product_id
GROUP BY 
    c.customer_id,
    c.customer_name
ORDER BY total_revenue DESC;


