--Q11 Find the total quantity sold for each product.

SELECT 
    p.product_id,
    p.product_name,
    SUM(o.quantity) AS total_quantity
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity DESC;

--Q12 Find the total revenue generated by each product.

SELECT 
    p.product_id,
    p.product_name,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;

--Q13 Find the top 5 products based on revenue.

SELECT 
    p.product_id,
    p.product_name,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
limit 5;

--Q14 Find revenue by product category.

SELECT 
    p.category,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

--Q15 Find the average product price for each category.

SELECT 
    category,
    avg(price) AS average
FROM 
products 
GROUP BY category
ORDER BY average DESC;

--Q16 Find the best-selling product based on quantity sold.

SELECT 
    product_id,
    sum(quantity) as total_quantity
FROM orders 
group by product_id
order by total_quantity desc
limit 1;



